config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get   'tasks',          to: 'tasks#index'

  get   'tasks/new',      to: 'tasks#new', as: :new_task
  post  'tasks',          to: 'tasks#create'

  # NB: The `show` route needs to be *after* `new` route.
  get   'tasks/:id',      to: 'tasks#show', as: :task

  get   'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id',      to: 'tasks#update'

  delete'tasks/:id',      to: 'tasks#destroy'

  post 'completetask/:id', to: 'tasks#done', as: :done
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# TasksController does something
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def done
    @task = Task.find(params[:id])
    @task.completed = !@task.completed
    @task.save
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" integrity="sha384-PmY9l28YgO4JwMKbTvgaS7XNZJ30MK9FAZjjzXtlqyZCqBY6X6bXIkM++IkyinN+" crossorigin="anonymous">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit your Task</h1>
<%= form_for(@task) do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>

<%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to "Return", tasks_path %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
    <%= link_to task do %><div class="card">
      <li>
        <p>Task name: <%= task.title %></p>
        <p>Completed: <%= task.completed %></p>
      </li>
    </div>
    <div>
      <%= link_to done_path(task), method: :post do %>
      <input type="checkbox" id="check" class="form-check-input">
      <% end %>
    </div>
    <% end %>
    <div class="btn btn-danger">
      <%= link_to "Delete", task_path(task), method: :delete%>
    </div>
    <% end %>
  </ul>
  <%= link_to "+ Add a new task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<h1>Create a new Task</h1>
<%= form_for @task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to "Return", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<h1><%= @task.completed %></h1>
<%= link_to "Return", tasks_path %>